const KEY="SIS_PRO_DB",SESSION="SIS_PRO_SESSION",THEME="SIS_PRO_THEME";
const seed={
users:[
{id:"u1",email:"admin@westlake.edu",password:"admin123",name:"Dr. Ananya Rao",role:"admin"},
{id:"u2",email:"faculty@westlake.edu",password:"faculty123",name:"Prof. Arjun Kumar",role:"faculty"},
{id:"u3",email:"student@westlake.edu",password:"student123",name:"Prithi Kumar",role:"student"}],
departments:[{id:"d1",name:"Computer Science & Engineering",code:"CSE"},{id:"d2",name:"Information Technology",code:"IT"},{id:"d3",name:"Electronics & Communication",code:"ECE"},{id:"d4",name:"Mechanical Engineering",code:"MECH"}],
courses:[{id:"c1",name:"B.E. Computer Science",code:"BE-CSE",duration:4,department:"d1"},{id:"c2",name:"B.Tech Information Technology",code:"BTECH-IT",duration:4,department:"d2"},{id:"c3",name:"B.E. Electronics",code:"BE-ECE",duration:4,department:"d3"}],
subjects:[{id:"s1",name:"Programming in C",code:"CS101",semester:1,credits:4},{id:"s2",name:"Database Management Systems",code:"CS301",semester:3,credits:4},{id:"s3",name:"Computer Networks",code:"CS401",semester:4,credits:3},{id:"s4",name:"Web Technologies",code:"CS302",semester:3,credits:3}],
students:[
{id:"u3",register:"24CSE001",name:"Prithi k",email:"student@westlake.edu",phone:"9876543210",department:"d1",course:"c1",year:2,semester:3,address:"Tamil Nadu"},
{id:"st2",register:"24CSE002",name:"Priya Sharma",email:"priya@westlake.edu",phone:"9876500001",department:"d1",course:"c1",year:2,semester:3,address:"Chennai"},
{id:"st3",register:"25IT001",name:"Rahul Menon",email:"rahul@westlake.edu",phone:"9876500002",department:"d2",course:"c2",year:1,semester:1,address:"Madurai"},
{id:"st4",register:"23ECE014",name:"Kavya Raj",email:"kavya@westlake.edu",phone:"9876500003",department:"d3",course:"c3",year:3,semester:5,address:"Coimbatore"},
{id:"st5",register:"24CSE018",name:"Vishal Kumar",email:"vishal@westlake.edu",phone:"9876500004",department:"d1",course:"c1",year:2,semester:3,address:"Trichy"}],
faculty:[{id:"u2",employee:"FAC001",name:"Prof. Arjun Kumar",email:"faculty@westlake.edu",department:"d1",designation:"Assistant Professor"},{id:"f2",employee:"FAC002",name:"Dr. Meena Shah",email:"meena@westlake.edu",department:"d2",designation:"Associate Professor"}],
attendance:[],
marks:[
{id:"m1",student:"u3",subject:"s1",exam:"Internal Assessment 1",marks:82,max:100},{id:"m2",student:"u3",subject:"s2",exam:"Internal Assessment 1",marks:76,max:100},{id:"m3",student:"u3",subject:"s4",exam:"Internal Assessment 1",marks:88,max:100},
{id:"m4",student:"st2",subject:"s1",exam:"Internal Assessment 1",marks:91,max:100}],
fees:[{id:"f1",student:"u3",type:"Tuition Fee",amount:50000,paid:35000,due:"2026-10-15"},{id:"f2",student:"u3",type:"Exam Fee",amount:2500,paid:2500,due:"2026-09-20"},{id:"f3",student:"st2",type:"Tuition Fee",amount:50000,paid:50000,due:"2026-09-10"}],
notices:[{id:"n1",title:"Internal Assessment Results Published",body:"Students can now view their latest internal assessment marks.",date:"2026-09-25"},{id:"n2",title:"Fee Payment Reminder",body:"Students with outstanding fees should complete payment before the due date.",date:"2026-09-24"},{id:"n3",title:"Department Meeting",body:"Faculty meeting will be held in Seminar Hall A at 2:00 PM.",date:"2026-09-23"}],
activity:[{text:"Internal Assessment marks updated",time:"10 min ago",icon:"✓"},{text:"New student profile created",time:"1 hr ago",icon:"+"},{text:"Fee payment recorded",time:"3 hrs ago",icon:"₹"}]
};
for(let i=0;i<20;i++){seed.attendance.push({id:"a"+i,student:i%2?"st2":"u3",subject:["s1","s2","s4"][i%3],date:`2026-09-${String(5+(i%18)).padStart(2,"0")}`,status:i%6===0?"Absent":"Present"})}
let db=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(seed); save();
let user=null,page=location.hash.slice(1)||"home";

function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function uid(p="id"){return p+Date.now()+Math.random().toString(16).slice(2)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function money(v){return "₹"+Number(v||0).toLocaleString("en-IN")}
function initials(n){return String(n||"U").split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}
function student(id){return db.students.find(x=>x.id===id)}
function subject(id){return db.subjects.find(x=>x.id===id)}
function dept(id){return db.departments.find(x=>x.id===id)?.name||"-"}
function course(id){return db.courses.find(x=>x.id===id)?.name||"-"}
function toast(msg){let t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2400)}
function stat(icon,label,value,trend=""){
return `<div class="card stat-card"><div class="stat-top"><span class="stat-icon">${icon}</span></div><h3>${value}</h3><p>${label}</p>${trend?`<div class="trend">${trend}</div>`:""}</div>`}

function fillDemo(role){let x={admin:["admin@westlake.edu","admin123"],faculty:["faculty@westlake.edu","faculty123"],student:["student@westlake.edu","student123"]}[role];email.value=x[0];password.value=x[1]}
function demoInfo(e){e.preventDefault();toast("Use one of the Quick demo roles below.")}
showPassword.onclick=()=>password.type=password.type==="password"?"text":"password";
loginForm.onsubmit=e=>{e.preventDefault();let x=db.users.find(u=>u.email.toLowerCase()===email.value.trim().toLowerCase()&&u.password===password.value);if(!x){loginError.textContent="Invalid credentials. Please try again.";loginError.classList.remove("hidden");return}user=x;localStorage.setItem(SESSION,user.id);loginError.classList.add("hidden");openApp()}
function openApp(){loginScreen.classList.add("hidden");app.classList.remove("hidden");renderNav();render()}
function logout(){localStorage.removeItem(SESSION);location.reload()}
logoutBtn.onclick=logout;menuBtn.onclick=()=>sidebar.classList.toggle("open");
function toggleProfileMenu(){profileDropdown.classList.toggle("hidden")}
function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem(THEME,document.body.classList.contains("dark")?"dark":"light")}
if(localStorage.getItem(THEME)==="dark")document.body.classList.add("dark")

const menus={
admin:[["home","▦","Overview"],["students","♙","Students"],["faculty","♟","Faculty"],["departments","⌘","Departments"],["courses","▣","Courses"],["subjects","◫","Subjects"],["attendance","◷","Attendance"],["marks","◈","Results & Marks"],["fees","₹","Fees"],["notices","◇","Announcements"],["reports","▤","Reports"]],
faculty:[["home","▦","Overview"],["students","♙","Students"],["attendance","◷","Attendance"],["marks","◈","Marks"],["notices","◇","Announcements"]],
student:[["home","▦","Dashboard"],["profile","◎","My Profile"],["attendance","◷","My Attendance"],["marks","◈","My Results"],["fees","₹","My Fees"],["notices","◇","Announcements"]]
};
function renderNav(){nav.innerHTML=`<div class="nav-section">MAIN MENU</div>`+(menus[user.role]||[]).map(x=>`<a href="#${x[0]}" data-page="${x[0]}" class="nav-link ${page===x[0]?"active":""}"><span class="nav-icon">${x[1]}</span>${x[2]}</a>`).join("");nav.querySelectorAll(".nav-link").forEach(a=>a.onclick=e=>{e.preventDefault();go(a.dataset.page)})}
function go(p){page=p;location.hash=p;renderNav();render();sidebar.classList.remove("open");profileDropdown.classList.add("hidden")}
function header(title,sub,button=""){document.getElementById("pageTitle").textContent=title;document.getElementById("topName").textContent=user.name;document.getElementById("topRole").textContent=user.role==="admin"?"Administrator":user.role==="faculty"?"Faculty":"Student";document.getElementById("topAvatar").textContent=initials(user.name);return `<div class="page-intro"><div><span class="eyebrow">${user.role==="admin"?"ADMINISTRATION":"ACADEMIC PORTAL"}</span><h1>${title}</h1><p>${sub}</p></div>${button}</div>`}

function render(){let html="";try{switch(page){case"home":html=home();break;case"students":html=students();break;case"faculty":html=faculty();break;case"departments":html=departments();break;case"courses":html=courses();break;case"subjects":html=subjects();break;case"attendance":html=attendance();break;case"marks":html=marks();break;case"fees":html=fees();break;case"notices":html=notices();break;case"profile":html=profile();break;case"reports":html=reports();break;default:page="home";html=home()}content.innerHTML=html}catch(e){content.innerHTML=`<div class="alert error">${esc(e.message)}</div>`}}

function home(){
if(user.role==="admin"){
let due=db.fees.reduce((a,x)=>a+Math.max(0,x.amount-x.paid),0),paid=db.fees.reduce((a,x)=>a+x.paid,0);
return header("Dashboard","A live overview of your institution's academic activity.")+
`<div class="grid g4">${stat("♙","Total Students",db.students.length,"↑ 8.4% this year")}${stat("♟","Faculty Members",db.faculty.length,"↑ 2 new this month")}${stat("▣","Departments",db.departments.length,"All active")}${stat("₹","Fee Outstanding",money(due),"Total collected "+money(paid))}</div>
<div class="grid g2" style="margin-top:17px"><div class="card"><div class="card-head"><h3>Enrollment Overview</h3><small>By department</small></div><div class="bar-chart">${db.departments.map((d,i)=>{let n=db.students.filter(s=>s.department===d.id).length;let h=Math.max(12,n/db.students.length*100);return `<div class="bar-col"><div class="bar" style="height:${h}%"></div><small>${d.code}</small></div>`}).join("")}</div></div>
<div class="card"><div class="card-head"><h3>Attendance Rate</h3><small>Current semester</small></div><div class="donut-row"><div style="position:relative"><div class="donut"></div><div class="donut-center">92%</div></div><div class="legend"><div><i></i>Present <b>92%</b></div><div><i class="gray"></i>Absent <b>8%</b></div><p class="muted">Based on recorded attendance</p></div></div></div></div>
<div class="grid g2" style="margin-top:17px"><div class="card"><div class="card-head"><h3>Recent Students</h3><button class="link-btn" onclick="go('students')">View all →</button></div>${studentRows(db.students.slice(-5).reverse(),false)}</div><div class="card"><div class="card-head"><h3>Recent Activity</h3><small>Today</small></div>${db.activity.map(a=>`<div class="notif-item"><b>${a.icon} &nbsp;${esc(a.text)}</b><span class="muted">${a.time}</span></div>`).join("")}</div></div>`
}
if(user.role==="faculty")return header("Faculty Dashboard","Monitor classes, attendance and student performance.")+
`<div class="grid g3">${stat("♙","Students",db.students.length)}${stat("◷","Attendance Today","92%","↑ 3.2% vs last week")}${stat("◈","Average Marks","81.4","Across your classes")}</div>
<div class="grid g2" style="margin-top:17px"><div class="card"><div class="card-head"><h3>Quick Actions</h3></div><div class="quick-grid"><button class="quick" onclick="go('attendance')">◷<b>Attendance</b><span>View records</span></button><button class="quick" onclick="go('marks')">◈<b>Enter Marks</b><span>Update results</span></button><button class="quick" onclick="go('students')">♙<b>Students</b><span>Browse students</span></button></div></div><div class="card"><div class="card-head"><h3>Latest Notices</h3></div>${db.notices.slice(0,3).map(n=>`<div class="notice"><h4>${esc(n.title)}</h4><p>${esc(n.body)}</p></div>`).join("")}</div></div>`;
let att=db.attendance.filter(x=>x.student===user.id),present=att.filter(x=>x.status==="Present").length,pct=att.length?Math.round(present/att.length*100):0,ms=db.marks.filter(x=>x.student===user.id),avg=ms.length?Math.round(ms.reduce((a,x)=>a+Number(x.marks),0)/ms.length):0,due=db.fees.filter(x=>x.student===user.id).reduce((a,x)=>a+Math.max(0,x.amount-x.paid),0);
return header("Student Dashboard","Good morning, "+user.name.split(" ")[0]+"! Here's your academic snapshot.")+
`<div class="grid g3">${stat("◷","Attendance",pct+"%","↑ 2.1% this month")}${stat("◈","Average Score",avg+"/100","Keep going!")}${stat("₹","Fees Due",money(due),due?"Payment pending":"All clear")}</div>
<div class="grid g2" style="margin-top:17px"><div class="card"><div class="card-head"><h3>Academic Performance</h3><button class="link-btn" onclick="go('marks')">Full results →</button></div><div class="bar-chart">${ms.map(m=>`<div class="bar-col"><div class="bar" style="height:${m.marks}%"></div><small>${subject(m.subject)?.code||"SUB"}</small></div>`).join("")}</div></div><div class="card"><div class="card-head"><h3>Upcoming / Notices</h3></div>${db.notices.slice(0,3).map(n=>`<div class="notice"><h4>${esc(n.title)}</h4><p>${esc(n.body)}</p></div>`).join("")}</div></div>`
}

function studentRows(arr,actions=true){return `<div class="table-wrap"><table><thead><tr><th>Student</th><th>Register No.</th><th>Department</th><th>Year</th>${actions?"<th>Action</th>":""}</tr></thead><tbody>${arr.map(s=>`<tr><td><div class="student-cell"><span class="tiny-avatar">${initials(s.name)}</span><span><b>${esc(s.name)}</b><small class="muted">${esc(s.email)}</small></span></div></td><td>${esc(s.register)}</td><td>${esc(dept(s.department))}</td><td>Year ${s.year}</td>${actions?`<td><button class="small-btn outline" onclick="viewStudent('${s.id}')">View</button></td>`:""}</tr>`).join("")}</tbody></table></div>`}

function students(){
if(user.role==="student")return profile();
return header("Students","Manage student profiles, academic details and enrollment.",`<button class="btn primary btn-sm" onclick="studentModal()">+ Add Student</button>`)+
`<div class="card"><div class="toolbar"><div class="search"><input id="studentSearch" placeholder="Search by name, register or email..." oninput="filterStudents()"></div><select id="deptFilter" onchange="filterStudents()" style="max-width:190px"><option value="">All departments</option>${db.departments.map(d=>`<option value="${d.id}">${d.code}</option>`).join("")}</select></div><div id="studentTable">${studentRows(db.students)}</div></div>`;
}
function filterStudents(){let q=(document.getElementById("studentSearch")?.value||"").toLowerCase(),d=document.getElementById("deptFilter")?.value||"";let arr=db.students.filter(s=>(!q||[s.name,s.register,s.email].some(v=>v.toLowerCase().includes(q)))&&(!d||s.department===d));document.getElementById("studentTable").innerHTML=studentRows(arr)}
function viewStudent(id){let s=student(id);openModal("STUDENT PROFILE",s.name,`<div class="profile-card"><div class="big-avatar">${initials(s.name)}</div><div><h3>${esc(s.name)}</h3><p class="muted">${esc(s.register)} • ${esc(dept(s.department))}</p></div></div><hr><div class="info-list"><div><span>Email</span><b>${esc(s.email)}</b></div><div><span>Phone</span><b>${esc(s.phone)}</b></div><div><span>Course</span><b>${esc(course(s.course))}</b></div><div><span>Year / Semester</span><b>${s.year} / ${s.semester}</b></div><div><span>Address</span><b>${esc(s.address)}</b></div></div>`)}
function studentModal(){openModal("NEW STUDENT","Add Student",formStudent())}
function formStudent(){return `<form onsubmit="saveStudent(event)" class="form-grid"><div><label>Full Name</label><input name="name" required></div><div><label>Register Number</label><input name="register" required></div><div><label>Email</label><input name="email" type="email" required></div><div><label>Phone</label><input name="phone"></div><div><label>Department</label><select name="department">${db.departments.map(d=>`<option value="${d.id}">${d.name}</option>`).join("")}</select></div><div><label>Course</label><select name="course">${db.courses.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select></div><div><label>Year</label><select name="year"><option>1</option><option>2</option><option>3</option><option>4</option></select></div><div><label>Semester</label><select name="semester">${[1,2,3,4,5,6,7,8].map(x=>`<option>${x}</option>`).join("")}</select></div><div class="full-col"><label>Address</label><textarea name="address"></textarea></div><div class="full-col modal-actions"><button type="button" class="btn outline" onclick="closeModal()">Cancel</button><button class="btn primary">Save Student</button></div></form>`}
function saveStudent(e){e.preventDefault();let f=new FormData(e.target),x=Object.fromEntries(f.entries());x.id=uid("st");x.year=+x.year;x.semester=+x.semester;db.students.push(x);db.activity.unshift({text:"New student profile created",time:"Just now",icon:"+"});save();closeModal();toast("Student added successfully");render()}

function faculty(){return header("Faculty","Faculty directory and teaching assignments.",`<button class="btn primary btn-sm" onclick="facultyModal()">+ Add Faculty</button>`)+`<div class="card">${facultyTable()}</div>`}
function facultyTable(){return `<div class="table-wrap"><table><thead><tr><th>Faculty</th><th>Employee ID</th><th>Department</th><th>Designation</th><th>Email</th></tr></thead><tbody>${db.faculty.map(f=>`<tr><td><div class="student-cell"><span class="tiny-avatar">${initials(f.name)}</span><b>${esc(f.name)}</b></div></td><td>${f.employee}</td><td>${esc(dept(f.department))}</td><td>${esc(f.designation)}</td><td>${esc(f.email)}</td></tr>`).join("")}</tbody></table></div>`}
function facultyModal(){openModal("NEW FACULTY","Add Faculty",`<form onsubmit="saveFaculty(event)" class="form-grid"><div><label>Name</label><input name="name" required></div><div><label>Employee ID</label><input name="employee" required></div><div><label>Email</label><input name="email" type="email" required></div><div><label>Designation</label><input name="designation" value="Assistant Professor"></div><div><label>Department</label><select name="department">${db.departments.map(d=>`<option value="${d.id}">${d.name}</option>`).join("")}</select></div><div class="full-col modal-actions"><button type="button" class="btn outline" onclick="closeModal()">Cancel</button><button class="btn primary">Save Faculty</button></div></form>`)}
function saveFaculty(e){e.preventDefault();let x=Object.fromEntries(new FormData(e.target));x.id=uid("f");db.faculty.push(x);save();closeModal();toast("Faculty added");render()}

function departments(){return header("Departments","Academic departments and organizational structure.",`<button class="btn primary btn-sm" onclick="simpleAdd('department')">+ Add Department</button>`)+`<div class="grid g3">${db.departments.map(d=>`<div class="card"><div class="stat-top"><span class="stat-icon">⌘</span><span class="muted">${d.code}</span></div><h3 style="margin-top:15px;font-size:15px">${esc(d.name)}</h3><p class="muted">${db.students.filter(s=>s.department===d.id).length} students • ${db.courses.filter(c=>c.department===d.id).length} courses</p></div>`).join("")}</div>`}
function courses(){return header("Courses","Programs offered across departments.",`<button class="btn primary btn-sm" onclick="simpleAdd('course')">+ Add Course</button>`)+`<div class="card"><div class="table-wrap"><table><thead><tr><th>Course</th><th>Code</th><th>Department</th><th>Duration</th><th>Students</th></tr></thead><tbody>${db.courses.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${c.code}</td><td>${esc(dept(c.department))}</td><td>${c.duration} years</td><td>${db.students.filter(s=>s.course===c.id).length}</td></tr>`).join("")}</tbody></table></div></div>`}
function subjects(){return header("Subjects","Manage subjects, semesters and credits.",`<button class="btn primary btn-sm" onclick="simpleAdd('subject')">+ Add Subject</button>`)+`<div class="card"><div class="table-wrap"><table><thead><tr><th>Code</th><th>Subject</th><th>Semester</th><th>Credits</th></tr></thead><tbody>${db.subjects.map(s=>`<tr><td>${s.code}</td><td><b>${esc(s.name)}</b></td><td>${s.semester}</td><td>${s.credits}</td></tr>`).join("")}</tbody></table></div></div>`}
function simpleAdd(type){let map={department:["Department name","Code"],course:["Course name","Code"],subject:["Subject name","Subject code"]}[type];let a=prompt(map[0]);if(!a)return;let b=prompt(map[1]);if(!b)return;if(type==="department")db.departments.push({id:uid("d"),name:a,code:b});if(type==="course")db.courses.push({id:uid("c"),name:a,code:b,duration:4,department:db.departments[0].id});if(type==="subject")db.subjects.push({id:uid("s"),name:a,code:b,semester:1,credits:3});save();toast("Saved successfully");render()}

function attendance(){let rows=db.attendance.filter(a=>user.role==="student"?a.student===user.id:true);let present=rows.filter(a=>a.status==="Present").length,pct=rows.length?Math.round(present/rows.length*100):0;return header(user.role==="student"?"My Attendance":"Attendance","Track daily attendance and class participation.",user.role!=="student"?`<button class="btn primary btn-sm" onclick="attendanceModal()">+ Mark Attendance</button>`:"")+`<div class="grid g3" style="margin-bottom:17px">${stat("◷","Attendance Rate",pct+"%")}${stat("✓","Present",present)}${stat("×","Absent",rows.filter(x=>x.status==="Absent").length)}</div><div class="card"><div class="toolbar"><h3>Attendance Records</h3><span class="muted">${rows.length} records</span></div><table><thead><tr><th>Date</th><th>Student</th><th>Subject</th><th>Status</th></tr></thead><tbody>${rows.slice().reverse().map(a=>`<tr><td>${a.date}</td><td>${esc(student(a.student)?.name)}</td><td>${esc(subject(a.subject)?.code)} - ${esc(subject(a.subject)?.name)}</td><td><span class="status ${a.status==="Present"?"present":"absent"}">${a.status}</span></td></tr>`).join("")}</tbody></table></div>`}
function attendanceModal(){openModal("ATTENDANCE","Mark Attendance",`<form onsubmit="saveAttendance(event)"><label>Student</label><select name="student">${db.students.map(s=>`<option value="${s.id}">${s.register} — ${s.name}</option>`).join("")}</select><label>Subject</label><select name="subject">${db.subjects.map(s=>`<option value="${s.id}">${s.code} — ${s.name}</option>`).join("")}</select><label>Date</label><input type="date" name="date" value="${new Date().toISOString().slice(0,10)}"><label>Status</label><select name="status"><option>Present</option><option>Absent</option><option>Leave</option></select><div class="modal-actions"><button type="button" class="btn outline" onclick="closeModal()">Cancel</button><button class="btn primary">Save</button></div></form>`)}
function saveAttendance(e){e.preventDefault();let x=Object.fromEntries(new FormData(e.target));x.id=uid("a");db.attendance.push(x);save();closeModal();toast("Attendance saved");render()}

function marks(){let rows=db.marks.filter(a=>user.role==="student"?a.student===user.id:true),avg=rows.length?Math.round(rows.reduce((a,x)=>a+Number(x.marks),0)/rows.length):0;return header(user.role==="student"?"My Results":"Results & Marks","View assessment performance and examination results.",user.role!=="student"?`<button class="btn primary btn-sm" onclick="marksModal()">+ Enter Marks</button>`:"")+`<div class="grid g3" style="margin-bottom:17px">${stat("◈","Average Score",avg+"/100")}${stat("★","Highest Score",rows.length?Math.max(...rows.map(x=>+x.marks)):"-")}${stat("▤","Assessments",rows.length)}</div><div class="card"><table><thead><tr><th>Student</th><th>Exam</th><th>Subject</th><th>Score</th><th>Performance</th></tr></thead><tbody>${rows.map(a=>{let p=Math.round(a.marks/a.max*100);return `<tr><td>${esc(student(a.student)?.name)}</td><td>${esc(a.exam)}</td><td>${esc(subject(a.subject)?.code)}</td><td><b>${a.marks}/${a.max}</b></td><td style="min-width:150px"><div class="progress"><i style="width:${p}%"></i></div><small class="muted">${p}%</small></td></tr>`}).join("")}</tbody></table></div>`}
function marksModal(){openModal("MARK ENTRY","Enter Student Marks",`<form onsubmit="saveMarks(event)"><label>Student</label><select name="student">${db.students.map(s=>`<option value="${s.id}">${s.register} — ${s.name}</option>`).join("")}</select><label>Subject</label><select name="subject">${db.subjects.map(s=>`<option value="${s.id}">${s.code} — ${s.name}</option>`).join("")}</select><label>Assessment</label><select name="exam"><option>Internal Assessment 1</option><option>Internal Assessment 2</option><option>Semester Examination</option></select><div class="form-grid"><div><label>Marks</label><input name="marks" type="number" min="0" max="100" required></div><div><label>Maximum</label><input name="max" value="100" type="number"></div></div><div class="modal-actions"><button type="button" class="btn outline" onclick="closeModal()">Cancel</button><button class="btn primary">Save Marks</button></div></form>`)}
function saveMarks(e){e.preventDefault();let x=Object.fromEntries(new FormData(e.target));x.id=uid("m");x.marks=+x.marks;x.max=+x.max;db.marks.push(x);db.activity.unshift({text:"Assessment marks updated",time:"Just now",icon:"✓"});save();closeModal();toast("Marks saved");render()}

function fees(){let rows=db.fees.filter(a=>user.role==="student"?a.student===user.id:true),total=rows.reduce((a,x)=>a+x.amount,0),paid=rows.reduce((a,x)=>a+x.paid,0);return header(user.role==="student"?"My Fees":"Fees & Payments","Track tuition, examination and other fee payments.",user.role==="admin"?`<button class="btn primary btn-sm" onclick="feeModal()">+ Add Fee</button>`:"")+`<div class="grid g3" style="margin-bottom:17px">${stat("₹","Total Fee",money(total))}${stat("✓","Collected",money(paid))}${stat("!","Outstanding",money(total-paid))}</div><div class="card"><table><thead><tr><th>Student</th><th>Fee Type</th><th>Amount</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>${rows.map(x=>{let b=Math.max(0,x.amount-x.paid);return `<tr><td>${esc(student(x.student)?.name)}</td><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td>${money(x.paid)}</td><td>${money(b)}</td><td><span class="status ${b?"due":"paid"}">${b?"Due":"Paid"}</span></td></tr>`}).join("")}</tbody></table></div>`}
function feeModal(){openModal("FEE RECORD","Add Fee Record",`<form onsubmit="saveFee(event)"><label>Student</label><select name="student">${db.students.map(s=>`<option value="${s.id}">${s.register} — ${s.name}</option>`).join("")}</select><label>Fee Type</label><select name="type"><option>Tuition Fee</option><option>Exam Fee</option><option>Hostel Fee</option><option>Library Fee</option></select><div class="form-grid"><div><label>Amount</label><input name="amount" type="number" required></div><div><label>Paid</label><input name="paid" type="number" value="0"></div></div><label>Due Date</label><input name="due" type="date"><div class="modal-actions"><button type="button" class="btn outline" onclick="closeModal()">Cancel</button><button class="btn primary">Save Fee</button></div></form>`)}
function saveFee(e){e.preventDefault();let x=Object.fromEntries(new FormData(e.target));x.id=uid("f");x.amount=+x.amount;x.paid=+x.paid;db.fees.push(x);save();closeModal();toast("Fee record added");render()}

function notices(){return header("Announcements","Important academic and campus updates.",user.role==="admin"?`<button class="btn primary btn-sm" onclick="noticeModal()">+ New Announcement</button>`:"")+db.notices.map(n=>`<div class="notice"><h4>${esc(n.title)}</h4><p>${esc(n.body)}</p><p style="margin-top:7px;font-size:9px">${n.date}</p></div>`).join("")}
function noticeModal(){openModal("ANNOUNCEMENT","Publish Notice",`<form onsubmit="saveNotice(event)"><label>Title</label><input name="title" required><label>Message</label><textarea name="body" rows="5" required></textarea><div class="modal-actions"><button type="button" class="btn outline" onclick="closeModal()">Cancel</button><button class="btn primary">Publish</button></div></form>`)}
function saveNotice(e){e.preventDefault();let x=Object.fromEntries(new FormData(e.target));x.id=uid("n");x.date=new Date().toISOString().slice(0,10);db.notices.unshift(x);save();closeModal();toast("Announcement published");render()}

function profile(){let s=student(user.id);return header("My Profile","Your personal and academic information.")+`<div class="grid g2"><div class="card"><div class="profile-card"><div class="big-avatar">${initials(user.name)}</div><div><h3>${esc(user.name)}</h3><p class="muted">${esc(user.email)}</p><span class="status present">Active Student</span></div></div></div><div class="card"><h3 style="margin-top:0">Academic Details</h3><div class="info-list"><div><span>Register Number</span><b>${esc(s?.register)}</b></div><div><span>Department</span><b>${esc(dept(s?.department))}</b></div><div><span>Course</span><b>${esc(course(s?.course))}</b></div><div><span>Year / Semester</span><b>${s?.year} / ${s?.semester}</b></div><div><span>Phone</span><b>${esc(s?.phone)}</b></div><div><span>Address</span><b>${esc(s?.address)}</b></div></div></div></div>`}
function reports(){let due=db.fees.reduce((a,x)=>a+Math.max(0,x.amount-x.paid),0),avg=Math.round(db.marks.reduce((a,x)=>a+Number(x.marks),0)/db.marks.length);return header("Reports","Institution-level summary for the current academic year.")+`<div class="grid g3">${stat("♙","Enrollment",db.students.length)}${stat("◈","Average Marks",avg+"%")}${stat("₹","Fee Outstanding",money(due))}</div><div class="card" style="margin-top:17px"><div class="card-head"><h3>Department Enrollment</h3><button class="btn outline btn-sm" onclick="window.print()">Print Report</button></div>${db.departments.map(d=>{let n=db.students.filter(s=>s.department===d.id).length,p=Math.round(n/db.students.length*100);return `<div style="margin:17px 0"><div class="toolbar"><b style="font-size:11px">${d.name}</b><span class="muted">${n} students</span></div><div class="progress"><i style="width:${p||3}%"></i></div></div>`}).join("")}</div>`}

function openModal(k,t,b){modalKicker.textContent=k;modalTitle.textContent=t;modalBody.innerHTML=b;modal.classList.remove("hidden")}
function closeModal(){modal.classList.add("hidden")}
function showNotifications(){let old=document.querySelector(".notification-panel");if(old){old.remove();return}let x=document.createElement("div");x.className="notification-panel";x.innerHTML=`<h3>Notifications</h3>${db.notices.slice(0,3).map(n=>`<div class="notif-item"><b>${esc(n.title)}</b><span class="muted">${n.date}</span></div>`).join("")}`;document.body.appendChild(x);setTimeout(()=>document.addEventListener("click",function h(e){if(!x.contains(e.target)){x.remove();document.removeEventListener("click",h)}}),0)}
function settings(){toast("Settings panel is available in the next module.")}
function toggleProfileMenu(){}
const saved=localStorage.getItem(SESSION);if(saved){user=db.users.find(x=>x.id===saved);if(user){loginScreen.classList.add("hidden");app.classList.remove("hidden");renderNav();render()}}
window.addEventListener("hashchange",()=>{page=location.hash.slice(1)||"home";if(user){renderNav();render()}});
